#!/usr/bin/python
# -*- coding: UTF-8 -*-

#--------------------------------------------------------------------
#File: 	webcam.py
#Author: F.Kesel
#Date: 	14.2.2016
#Purpose:Run the webcam program if enabled via website
#--------------------------------------------------------------------

import os, time, sys
from subprocess import call

webcamPath = "/home/frank/python/webcam/"

FNULL = open(os.devnull, 'w') #/dev/null for stdout and stderr

#Check if file start_cam exists (should be generated by webpage)
#then call md-program, which reads the cam and detects motion
if os.path.isfile(webcamPath + "start_cam"):
	call(["/home/frank/bin/md"], stdout=FNULL, stderr=FNULL)
else:
	sys.exit(0)

#md generates webcam.png (webcam picture) and if motion was detected
#the file motion_detect (signals that motion was detected if it exists)
# and the picture detect.png in case motion was detected
#copy these files from /home/frank to the webcam directory
if os.path.isfile("/home/frank/webcam.png"):
	call(["mv", "/home/frank/webcam.png", webcamPath + "webcam.png"], stdout=FNULL, stderr=FNULL)

if os.path.isfile("/home/frank/detected.png"):
	call(["mv", "/home/frank/detected.png", webcamPath + "detected.png"], stdout=FNULL, stderr=FNULL)

if os.path.isfile("/home/frank/motion_detected"):
	call(["mv", "/home/frank/motion_detected", webcamPath + "motion_detected"], stdout=FNULL, stderr=FNULL)
	#Change to write for all in order to be deleted by webserver
	call(["chmod", "a+w", webcamPath + "motion_detected"], stdout=FNULL, stderr=FNULL)


